### ISSUE TITLE
Set background of statusbar and navigation bar to white

### ISSUE THREAD

**Issue by xmha97** [Crazy-Marvin/Flashy#104]
Please set background of statusbar and navigation bar to white.

![IMG_20221111_182629_669.jpg](https://user-images.githubusercontent.com/23485114/201366068-8e0c183b-a29f-48b4-a6b5-5b6ddd9ba3d8.jpg)

![IMG_20221111_182829_798.jpg](https://user-images.githubusercontent.com/23485114/201366465-97e4c6b7-8a6a-4f9d-a133-c0c10f0216c5.jpg)

**Comment by CrazyMarvin** [comment]
Do you like the design in v1.5, @xmha97?

**Comment by CrazyMarvin** [comment]
I like the design since v1.5 and will close this issue.
