### ISSUE TITLE
Better quick tile icon

### ISSUE THREAD

**Issue by xmha97** [Crazy-Marvin/Flashy#105]
Please use a better icon for the quick tile.

![IMG_20221111_183217_992.jpg](https://user-images.githubusercontent.com/23485114/201367353-72adc033-c5d7-441a-86ed-37bfd8060c29.jpg)

**Comment by CrazyMarvin** [comment]
Thanks for your feedback. 
Are you able to design something for us?

**Comment by xmha97** [comment]
No, I am not a designer.

**Comment by CrazyMarvin** [comment]
What are your ideas?

As most phones have a flashlight as shortcut already I think going with a flash is a nice way so that it does not get mixed up. 🤔
Or would you like to have a similar symbol like the stock shortcut? 

Here is a screenshot from my default flashlight shortcut:
![Screenshot_2023-01-11-11-05-58-48_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/15004217/211777495-3dceb396-01e6-42ac-97e8-78bfc5181bff.jpg)

**Comment by xmha97** [comment]
Thanks for your reply, Yes.

**Comment by CrazyMarvin** [comment]
What do you think about using the [flash from the Material Design Icons](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:flash_on:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=flash&icon.platform=android)?

**Comment by xmha97** [comment]
> What do you think about using the [flash from the Material Design Icons](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:flash_on:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=flash&icon.platform=android)?
> 
> 

It's good. 👍

**Comment by CrazyMarvin** [comment]
On my phone it is already looking like the  [flash from the Material Design Icons](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:flash_on:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=flash&icon.platform=android), @xmha97.

![QuickTile](https://github.com/Crazy-Marvin/Flashy/assets/15004217/eeb4dc9a-cf58-4921-a6a8-45bca35a27f7)


@unbiaseduser, may you please verify that the [flash from the Material Design Icons](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:flash_on:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=flash&icon.platform=android) is already in use for the quick tile?

**Comment by unbiaseduser** [comment]
Yes, it's the exact same icon I downloaded from the website and used.

**Comment by CrazyMarvin** [comment]
Do you have another phone for testing, @xmha97?
