### ISSUE TITLE
Add AppShortcut

### ISSUE THREAD

**Issue by xmha97** [Crazy-Marvin/Flashy#106]
Please add an AppShortcut. (Like this app)

![IMG_20221111_184006_307.jpg](https://user-images.githubusercontent.com/23485114/201368631-86f01572-d343-462a-b811-078189f6e45a.jpg)

**Comment by CrazyMarvin** [comment]
That's a good idea.
Are you up for creating a PR?

**Comment by xmha97** [comment]
No, I am not a Android programmer.

**Comment by CrazyMarvin** [comment]
Which shortcuts would you like to have?

I would find those useful:
- Flashlight on
- Flashlight off
- SOS

Let me know if that is fine or if you have other ideas. Thanks. 👍

**Comment by xmha97** [comment]
Toggle flashlight (On/Off)

**Comment by Gzushgshsh** [comment]
The current icon looks very strange next to the applications, it's a little weird. Could you change it to look like a normal icon on the interface?

Something like this:
![Screenshot_2023-04-17-22-45-12.png](https://user-images.githubusercontent.com/95548091/232649200-2dc33f46-f683-4e82-b1a5-3a8cf9d27620.png)

**Comment by CrazyMarvin** [comment]
> The current icon looks very strange next to the applications, it's a little weird. Could you change it to look like a normal icon on the interface?
> 
> Something like this:
> ![Screenshot_2023-04-17-22-45-12.png](https://user-images.githubusercontent.com/95548091/232649200-2dc33f46-f683-4e82-b1a5-3a8cf9d27620.png)
> 
> 

I'm not sure what you mean.
May you please elaborate?

**Comment by Gzushgshsh** [comment]
Basically make the shortcut centralized and the same size as app shortcuts on the home screen. Make it look more natural with the rest of the interface. In a way that it looks like just another normal icon and doesn't look out of place

I don't know if I explained my idea well but that's more or less it

**Comment by CrazyMarvin** [comment]
Are you using Flashy or another app?

It's available on https://f-droid.org/en/packages/rocks.poopjournal.flashy/ and https://play.google.com/store/apps/details?id=rocks.poopjournal.flashy.

You see the widget on the left and the icon right to it:
![Flashy](https://user-images.githubusercontent.com/15004217/233196863-8b638530-16d8-456e-bad8-a8fe3bedfe74.jpg)

**Comment by CrazyMarvin** [comment]
@unbiaseduser, are you interested in developing app shortcuts?

**Comment by Gzushgshsh** [comment]
> Are you using Flashy or another app?
> 
> It's available on https://f-droid.org/en/packages/rocks.poopjournal.flashy/ and https://play.google.com/store/apps/details?id=rocks.poopjournal.flashy.
> 
> You see the widget on the left and the icon right to it:
> ![Flashy](https://user-images.githubusercontent.com/15004217/233196863-8b638530-16d8-456e-bad8-a8fe3bedfe74.jpg)
> 
> 

Flashy, is a good app!
![Screenshot_20230419-220607_One UI Home.jpg](https://user-images.githubusercontent.com/95548091/233231752-a32f78ff-b831-470b-a21f-4643bd9cdd3e.jpg)
