### ISSUE TITLE
App crash on Android 13 (API 33)

### ISSUE THREAD

**Issue by vuphong0x** [Crazy-Marvin/Flashy#117]
App crashes when using flashlight functions in API 33

**Comment by CrazyMarvin** [comment]
> App crashes when using flashlight functions in API 33

Thanks for the info.

Which device are you using? Is your phone rooted?

**Comment by vuphong0x** [comment]
I'm using Realme Q5 and it is not rooted

**Comment by CrazyMarvin** [comment]
> I'm using Realme Q5 and it is not rooted

Thanks for the info.

@unbiaseduser, may you please look into this?

**Comment by unbiaseduser** [comment]
Hello. Please install this debug apk [app-debug.zip](https://github.com/Crazy-Marvin/Flashy/files/10416868/app-debug.zip), take crash logs via ADB (there are plenty tutorials for that) and send it here. Thanks

**Comment by CrazyMarvin** [comment]
Does your app still crash, @vuphong0x?

**Comment by CrazyMarvin** [comment]
I got my hands on a [Nothing phone (1)](https://nothing.tech/) running [Android 13](https://www.android.com/android-13/).
Version 1.5 crashed but version 1.6 is working fine so far, @unbiaseduser. 👍
@vuphong0x, may you please verify this on your end too?
