### ISSUE TITLE
Support Wear OS by Google

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Flashy#144]
What do you think about [Wear OS by Google](https://wearos.google.com/)?

| ![Frame 11](https://github.com/Crazy-Marvin/Flashy/assets/15004217/0f7f5826-e83d-4a5f-ae26-e60d386881b4) | ![Frame 12](https://github.com/Crazy-Marvin/Flashy/assets/15004217/c9c3a0c9-8dc7-4a5d-9547-c731dcf6261a) | ![Frame 13](https://github.com/Crazy-Marvin/Flashy/assets/15004217/022364ba-8712-41b6-bb2c-dcc494bd7f9a) |

**Comment by CrazyMarvin** [comment]
@linsui, do we have to update the F-Droid setup for this?   
The code for the Wear OS companion app will be in a separate folder `wear`.

**Comment by linsui** [comment]
I guess the scanner will complain about non-free deps in the wear folder. So you need to add it to `rm:` and remove it from settings.gradle.

**Comment by CrazyMarvin** [comment]
> I guess the scanner will complain about non-free deps in the wear folder. So you need to add it to `rm:` and remove it from settings.gradle.

I just opened a MR on GitLab: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14316.
I also addressed https://gitlab.com/fdroid/fdroiddata/-/issues/2128# which I did not see until today. Sorry for the late reply.

**Comment by CrazyMarvin** [comment]
@karimapps will develop this feature. 👍

**Comment by CrazyMarvin** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14397
