### ISSUE TITLE
Android 14 is out - 34 api - compile and target

### ISSUE THREAD

**Issue by inson1** [Crazy-Marvin/Flashy#169]

**Comment by CrazyMarvin** [comment]
I updated them in https://github.com/Crazy-Marvin/Flashy/commit/660fa92f51523d7eb1ad1e681029662526b7180f.
Are you running Android 14 and experiencing any issues?

**Comment by inson1** [comment]
@CrazyMarvin No, not yet, I just know there was new version, so looked and you still was still on previous version :)

Did you try emulator? If yes, feel free to close it :) or I wil :)

**Comment by CrazyMarvin** [comment]
Please check it. I don't have time now.
I hope to create a new release in January.
