### ISSUE TITLE
Crowdin Integration

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Flashy#21]
At the moment Crowdin only serves for the Google Play texts. 
It would be great to add the strings of the app itself and make it possible to translate everything on Crowdin. 
For that a [crowdin.yaml](https://support.crowdin.com/configuration-file/) configuration file is needed.

**Comment by comradekingu** [comment]
Weblate has fastlane support too, makes sense to me.

**Comment by CrazyMarvin** [comment]
I tried to register for [Hosted Weblate](https://hosted.weblate.org/about/) but they did not accept my project. Crowdin warmly welcomed me so I will stay with them. I appreciate that Weblate has better ToS though.

**Comment by comradekingu** [comment]
I have never seen this project on there, you can self-register projects now, and then ask for approval once done. This project complies with the requirements of the Libre plan :)

**Comment by CrazyMarvin** [comment]
Flashy is on Hosted Weblate now. 😎
