### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Flashy#27]
![widet_1](https://user-images.githubusercontent.com/15004217/193667688-3569c5e0-e853-40b7-a6ef-27caadcc83b3.jpg)

A flash icon which activates the flashlight was added in v1.3.

![widet_2](https://user-images.githubusercontent.com/15004217/193667693-b124a524-23b9-4136-b0b7-fe34abc41e5a.png)

Is something like this with a slider for the screen brightness possible too?

**Comment by CrazyMarvin** [comment]
May you do a second widget that is able to adjust the screen brightness, @unbiaseduser? 🤔

![widet_2](https://user-images.githubusercontent.com/15004217/193668081-62d1b548-2206-4d55-ad6f-31952c383afc.png)

**Comment by unbiaseduser** [comment]
@CrazyMarvin Two things:
- Unfortunately, you cannot have a slider on a widget.
- When the user changes brightness via the system brightness bar (on the quick settings), the app has no way to know when the brightness has changed, so it cannot update the UI.

**Comment by unbiaseduser** [comment]
Btw, @CrazyMarvin can you give feedback on this new widget design?
![IMG_20221004_163536](https://user-images.githubusercontent.com/95969852/193787069-adf9a6d2-c3b3-4a96-a177-01587a2aaf33.jpg)
![IMG_20221004_163517](https://user-images.githubusercontent.com/95969852/193787110-7b7ac50b-f78e-4db7-aabf-4cffd261c0db.jpg)

**Comment by CrazyMarvin** [comment]
Thanks for the explanation. Then we will go with the widet as in #63.
