### ISSUE TITLE
Colourful Screen

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Flashy#35]
> I don't know if you have any time to hear out stupid suggestions but have you ever considered adding colors to the screen?
> 
> I would really enjoy being able to set screen red for a non invasive light.

A user would like to have the option to change the color of the screen. What do you think about it?

**Comment by prathamesh-2002** [comment]
Yes, can I work on adding this toggle?

**Comment by CrazyMarvin** [comment]
> Yes, can I work on adding this toggle?

That would be great. 👍

**Comment by CrazyMarvin** [comment]
No feedback from @prathamesh-2002 so someone may pick this up. I would highly appreciate it.

**Comment by CrazyMarvin** [comment]
Are you interested to work on this, @unbiaseduser?

**Comment by CrazyMarvin** [comment]
@karimapps will develop this feature. 👍

**Comment by unbiaseduser** [comment]
Good. I haven't got enough free time recently, so it's great to see someone else doing stuff.

**Comment by CrazyMarvin** [comment]
> Good. I haven't got enough free time recently, so it's great to see someone else doing stuff.

Yes, that's great. I'm happy about it too. 😊

**Comment by karimapps** [comment]
Hi
please explain it more , you want to chnage color in mobile app or in wear os app also please share the screen where you want to chnage color ? one thing more is the wear os standalone or comapnion app?
