### ISSUE TITLE
Avoid Camera permission

### ISSUE THREAD

**Issue by rusty-snake** [Crazy-Marvin/Flashy#41]
Other flashlight apps like Simple Flashlight work without Camera permission, so there seems to be a way to control the flashlight w/o Camera permission. For an app like Flashy that claims to be privacy friendly it would be good to use such less intrusive permissions or state why Camera permission is necessary.

**Comment by CrazyMarvin** [comment]
That's good to know. 😎
We investigated but did not find a possibility to use the flashlight without camera permission. Maybe the source you mentioned helps us. 👍
A PR would be highly appreciated because we won't find time in the near future.
