### ISSUE TITLE
Feedback on upcoming About page

### ISSUE THREAD

**Issue by unbiaseduser** [Crazy-Marvin/Flashy#61]
I'm making an About page for the app, and I'd like to show the UI I made. This is just a draft, I'll change it if you have a good suggestion. Do provide feedback, please. @CrazyMarvin @FahadSaleem
![Screenshot_20221003-233040832](https://user-images.githubusercontent.com/95969852/193630977-ef17172f-143b-4387-b9e4-c2e0886f766d.jpg)

**Comment by CrazyMarvin** [comment]
That's a good idea. 👍
Please use the About design from Vacation Days or To Don't.
They use the [Feather Icons](https://feathericons.com/). 
The designer will add the About page to the [mockup](https://www.figma.com/file/KVIWgF61t85hjMB4gMdS6I/Flashy?node-id=0%3A1) so you may easily copy it from there.
Feel welcome to add yourself too.

**Comment by unbiaseduser** [comment]
Alright, so do I have to remove the Cards (Developer and Contribute) or can I leave them there?
Anyway, here's the version with Feather icons:
![Screenshot_20221004-093525917 (1)](https://user-images.githubusercontent.com/95969852/193722725-eb3d5229-d1c4-4f8f-ba8c-7807d96230c5.jpg)
i'll probably ping you for good measure eh @CrazyMarvin ?

**Comment by CrazyMarvin** [comment]
You can see the About page for Vacation Days [here](https://www.figma.com/file/9Fk92SQVItIwAjVfsakopo/).

**Comment by unbiaseduser** [comment]
@CrazyMarvin what about now?
![Screenshot_20221005-101837487 (1)](https://user-images.githubusercontent.com/95969852/193973934-ae2cf0f3-1b64-4e9e-8646-2f790e25e423.jpg)

**Comment by unbiaseduser** [comment]
Also, in the mockup there are 2 icons in the bottom corners.
![2022-10-05 12_56_17-Flashy – Figma — Mozilla Firefox](https://user-images.githubusercontent.com/95969852/193991208-aeac0507-0bda-4b22-910e-fe32bd781922.png)
@CrazyMarvin What will they do?
I need to figure out where to put the About and Settings menu so I can work on #8 and this.

**Comment by CrazyMarvin** [comment]
The question mark links to a support page and the three dots open the Settings and About pages.
Handling it like in #68 is a good idea. 👍
We can pass on the support page I suppose.

**Comment by unbiaseduser** [comment]
@CrazyMarvin Does the About page look fine to you? I tried to follow the Vacation Days mockup the closest I can.
About the `third party license` section, I don't actually know the website for the `CircularSeekBar` library, so can I pass on the section? Or just visually include it without going to its website when clicked?

**Comment by CrazyMarvin** [comment]
Yes, it should be fine. Thanks! 👍

You may use https://github.com/tankery/CircularSeekBar as website.
