### ISSUE TITLE
Switching between camera light and screen should not switch off

### ISSUE THREAD

**Issue by sphh** [Crazy-Marvin/Flashy#8]
Thanks for this. It's the best!

I noticed that whenever I switch between the camera light and the screen, the light turns off. Is this by design? Personally I would expect to keep the light on ...

**Comment by CrazyMarvin** [comment]
Thank you so much for your kind words.
We will think about it, I am still unsure what works best. 
Maybe a menu in the upper right with such a setting would make sense. 🤔

**Comment by sphh** [comment]
Well, a configurable option is always an option! It is not an easy decision, because some like it that way and some the other way.

I did not want to burden you with implementing a configuration item, but a tiny three-dots-menu does not take much space...

**Comment by CrazyMarvin** [comment]
May you work on this too, @unbiaseduser?

**Comment by sphh** [comment]
Many, many thanks!
