### ISSUE TITLE
Turning screen light off dies not restore previous brightness

### ISSUE THREAD

**Issue by rusty-snake** [Crazy-Marvin/Flashy#86]
### STR

- turn screen light on
- turn screen light off

### Expected behavior

Brightness gets reset to the value before turning the screen light on (i.e. the value managed by the os)

### Actual behavior

Brightness gets set to darkest value.

---

- GrapheneOS (AOSP 13)
- Flashy 1.4

**Comment by unbiaseduser** [comment]
Hello. Please try this APK and see if it fixes your issue. (since unfortunately I can't reproduce it on an Android 11 phone.)
(I'm the dev of Flashy if you're wondering.)
[app-debug.zip](https://github.com/Crazy-Marvin/Flashy/files/9794377/app-debug.zip)

**Comment by rusty-snake** [comment]
Not reproducible with this version.

**Comment by unbiaseduser** [comment]
> Not reproducible with this version.

Great. I'll make a PR now.
