### ISSUE TITLE
SOS?

### ISSUE THREAD

**Issue by sphh** [Crazy-Marvin/Flashy#9]
Some other flashlights have the feature to emit a SOS sign. I hope that I will never need it, but it might make the difference. Are there any plans to include such a feature? Maybe a "simple" flashing light (with adjustable interval?) might also be useful to attract attention ...

**Comment by CrazyMarvin** [comment]
We will think about it.
In the meantime feel welcome to install [Morse](https://github.com/Crazy-Marvin/Morse) that offers such a feature.

**Comment by sphh** [comment]
Thanks, I'll look at it.

BTW if you find a way to make a really loud noise (and a quick way to switch it on - pull the headphone plug?), this app could become sort of a personal alarm (just thinking loudly...)

**Comment by CrazyMarvin** [comment]
> BTW if you find a way to make a really loud noise (and a quick way to switch it on - pull the headphone plug?), this app could become sort of a personal alarm (just thinking loudly...)

Can you please elaborate what you mean with that? Maybe a little sketch (can be hand-drawn) with the interface might be helpful.

**Comment by sphh** [comment]
My somewhat crazy idea was the following: A personal alarm (https://en.wikipedia.org/wiki/Personal_alarm) attracts attention. And a flashing light also attracts attention. (That was the train of thought, which brought me to the personal alarm.) Both combined should attract even more attention.

IMHO the critical point with personal alarms are the quick activation: Unlocking the phone, fumbling to find the alarm app, opening it, pressing some buttons will not work. It has to be really quick. I once owned an alarm, where you pulled a plug and it started. That's where the idea of pulling the headphone out of the phone comes from. So you start the app, plug in a headphone and lock the phone. In case you need to attract attention, you yank out the headphone and the alarm goes off.

But - and that's critical - the phone must be able to make a really loud noise. I don't know, if that's possible. There are some apps on Google Play Store (search for "panic alarm") which claim they can do it, but they have the problem described above. I've not tried them.

Or just keep this app simple and a torchlight.

**Comment by CrazyMarvin** [comment]
Ah, now I understand your idea. 

I don't think that I will implement such a personal alarm feature with the headphone activation. But maybe another point below _SOS_ would possible that plays a loud sound. 🤔

The personal alarm with headphone activation might be a case for an extra app. Unfortunately I don't have time for it. But you might try it yourself or hire a freelancer.
It should be possible using system access to play a sound on maximum volume. I tried an app long time ago that locks the phone in case it gets stolen and plays a tune (something like "Attention, I am a stolen smartphone" *beep* *beep* *beep*) and that was very loud. 
I suppose you use a smartphone without installed Google services and cannot try those apps at the moment, right? Do you have the possibility to try them on another device? Perhaps the developers of those apps can help you.
You can contact me regarding those personal alarms app via e-mail too.

Thanks for your input.

**Comment by sphh** [comment]
There are many apps playing a loud noise, but all are fiddly to start and IMHO not working as a personal alarm. I wonder, why no such app exists. Perhaps, because all the programmers writing apps are men and women are more likely to want such an app...

Anyway, that was because my fantasy took me for a ride and not "proper" feature request. So no worries, keep the flash light a flash light! It's the best I have seen so far!

**Comment by CrazyMarvin** [comment]
Let's keep the issue open. I might implement a menu with _SOS_ and _Noise_ sometime.
